inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [ [ -1.5, 2.2 ],[ -0.3, 2.2 ],[ -2.3, 1.9 ] ]
  marching_cubes_bound: [ [ -1.5, 2.2 ],[ -0.3, 2.2 ],[ -2.3, 1.9 ] ]
  

data:
  datadir: data/neural_rgbd_data/morning_apartment
  trainskip: 1
  output: output/Synthetic/ma
  exp_name: demo