inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-2.5, 1.1],[-0.3, 1.1],[0.1, 3.9]]
  marching_cubes_bound: [[-2.5, 1.1],[-0.3, 1.1],[0.1, 3.9]]
  

data:
  datadir: data/neural_rgbd_data/thin_geometry
  trainskip: 1
  output: output/Synthetic/tg
  exp_name: demo

cam:
  near: 0
  far: 4