inherit_from: configs/Tum_dagger/tum.yaml
mapping:
  bound: [[-6.,6],[-5,6],[-1.,3.]] # [[-5.,5.],[-5.,5.],[-5.,5.]]
  marching_cubes_bound: [[-8.,7.5],[-7.5,7.5],[-1.,3.]] # [[-5.,5.],[-5.,5.],[-5.,5.]]

data:
  datadir: data/TUM/rgbd_dataset_freiburg3_long_office_household
  trainskip: 1
  output: output/TUM_dagger/fr_office
  exp_name: demo

cam:  #intrinsic is different per scene in TUM, this cam does not have distortion
  H: 480 
  W: 640
  fx: 535.4
  fy: 539.2
  cx: 320.1
  cy: 247.6
  crop_edge: 8
  crop_size: [384,512]
  near: 0
  far: 5