inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-1.0,6.1],[-3.4,1.9],[-3.1,0.8]]
  marching_cubes_bound: [[-0.9,6.0],[-3.3,1.8],[-3.0,0.7]]


data:
  datadir: data/Replica/room2
  trainskip: 1
  output: output/Replica/room2
  exp_name: demo